apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base/cpd-operators-cp4d-operator.yaml
  - instances/gitops-cp4d-instance-ibm-cpd-db2-instance.yaml
  - operators/gitops-cp4d-instance-ibm-cpd-db2-subscription.yaml
