apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitlement-key
  namespace: openshift-marketplace
spec:
  encryptedData:
    .dockerconfigjson: AgBgOYSHRtDT32iw1PDQshCa04basejBqmlLssZ1M3LuQakIo+5R9o7L77VUZaYAX96ayDFCGOt/bkz2PVqWLZ8el00Syahl401mTYyGlbBRYgt9G1CAJUgaiZYhq1oexCfM93SIwJYMAdBI9uuMupPSFduW+6o5xFar3qQRRycoBconFK/e3Qu8rfvxVUhRDZ3TGusJWLnpxuZms/7GmFas2jxZ55Qg4kXfu9E7aY7pDlCLHUW2Faf9XWdU/wu4ynCxk3ncxg3haCD7eZeG9GYFFWX6u0n/t/D0SBjn2J465hV4ELatl/TF3OEZuyR+C0hLkb/NXytAilQEx8OwXiXDtXOH/cmousFwDjXCv3RpgVdq0kZUGm8KbWhIlXBsCQM/nWyTsGK+C0e3umS2pCZIXSEadQPSBezi7H/rgs9Zh7DNDLS8dzRlIgmUsZXuDZIcPq2GUDvbjAtwk9I+36F3iThgSQjB+dsZUagX6KOrH0IBa1XVJqOAS2x92iXDrx4+vq3l0Yn9F8jVcULJcDh40lvTjuo01JEQq6IO+yCo4lFPfXiA0Hl7UBrkvZkl9Bf3BrZijApZ3gLj5gIXav44Ab+P/T96QFwU11ipTqNR8rnkSJCoDQ6uQpMU1ITdx4nf2KX3A2QzJfNYfbcvB7XGZnHj3y26aJmn2553NGG9WxbTh0ud9b/RKMegpAv/VUQE4gk0FoFzwOfUY5vou2qage+gkzC9+8PFTs3GJ+wMElUXAnCGsSrrM/xgFT7ANp+R0NuGOAp6+/J5TVt330Kc4oYjorhvVuzHb0BNr5fXwPceAYKFb8D6pT5zFp+sUaGB+GzxbZ0UlU+FHKZbzTbkO7iPs+mYxJLV0pkohhlmFttwr9eYcwN65gnrGoqdrqWj5sQnXccZnBWLcxgV5Udx3R19kHmA21dHOUyEG9v4x06yvODIaY7uFbO/6Snw5JIY1ZXIh4IgkG2LQ2xUPjvN8ToDYCbjKFpTATfk42rtqVxFyncL1A+cNjKlqMqF0E3igXEuX7aCvuW8ySj31WUm9o/3XRNEHAP46wzpgBqveuUvooTxLSh6O+7a5RtR9XcpCXbnu5QK0Jprn/VyiUIEHlJaCMTqn2Ilsl0SxagWs38Oz6lSympxCZpqvEVzijmecQXY6vfM1LkyJzkWt5crFNRypQUQEJF4J+S74fqg7/2Nor55/4LZCWDyjmd6OMCbL01wpIOpFZctQZxSzixoxlHY33vCAQu1xBvhdNsJnFRbmdBNZslvvHc1dlzmhzCADJ4vgwtMxnTWdQNCcH6MURROuBuWY/JZfg3odJ2+PfcJGo6fdk6h+4trB+sbpzSirFHGupAH+vbegg2R8UqrrnwOc3pkWvny5za3rDcgQAOe1ui3
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitlement-key
      namespace: openshift-marketplace
    type: kubernetes.io/dockerconfigjson

