apiVersion: v1
kind: Namespace
metadata:
  name: cpd-operators
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: cpd-operators-operator-group
  namespace: cpd-operators
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  targetNamespaces:
    - cpd-operators
---
