apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-cp4d-instance-ibm-cpd-db2-subscription
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: gitops-cp4d-instance
    server: https://kubernetes.default.svc
  project: 2-services
  source:
    path: payload/2-services/namespace/gitops-cp4d-instance/ibm-cpd-db2-subscription
    repoURL: https://github.com/se-test-sp/swe-local-test-db2
    targetRevision: main
    helm:
      releaseName: ibm-cpd-db2-subscription
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
