apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ibm-common-services-db2oltp-operandreg-sa-rbac
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ibm-common-services
    server: https://kubernetes.default.svc
  project: 1-infrastructure
  source:
    path: >-
      payload/1-infrastructure/namespace/ibm-common-services/db2oltp-operandreg-sa-rbac
    repoURL: https://github.com/se-test-sp/swe-local-test-db2
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
